### ISSUE TITLE
Error:(15, 0) Gradle DSL method not found: 'compile()'

### ISSUE THREAD

**Issue by bwzedev** [orhanobut/tracklytics#12]
can you help me please 

Error:(15, 0) Gradle DSL method not found: 'compile()'
Possible causes:<ul><li>The project 'worcipe' may be using a version of Gradle that does not contain the method.
<a href="open.wrapper.file">Open Gradle wrapper file</a></li><li>The build file may be missing a Gradle plugin.
<a href="apply.gradle.plugin">Apply Gradle plugin</a></li>
- build.gradle (project: worcipe)

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.5.0'

```
    // NOTE: Do not place your application dependencies here; they belong
    // in the individual module build.gradle files
   // ... other dependencies here

    compile('com.github.afollestad.material-dialogs:core:0.8.5.1@aar') {
        transitive = true
    }
}
```

}

allprojects {
    repositories {
        jcenter()
    }
}
- build.gradle (Modul: app)

apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"
    defaultConfig {
        applicationId "com.gabriel.workoutrecipes"
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    productFlavors {
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile('com.mikepenz:materialdrawer:4.6.1@aar') {
        transitive = true
    }
    compile 'com.android.support:appcompat-v7:22.2.1'
    compile 'com.android.support:design:24.0.0-alpha2'
    compile 'com.github.rey5137:material:1.2.2'
    compile 'com.afollestad:material-dialogs:0.7.9.1'
    compile 'se.emilsjolander:StickyScrollViewItems:1.1.0'
    compile 'com.melnykov:floatingactionbutton:1.3.0'
    compile 'com.android.support:cardview-v7:24.0.0-alpha2'
    compile 'com.android.support:recyclerview-v7:24.0.0-alpha2'
    compile 'com.etsy.android.grid:library:1.0.5'
    compile 'com.google.android.gms:play-services-ads:8.4.0'
    compile 'com.google.android.gms:play-services-analytics:8.4.0'
}

**Comment by orhanobut** [comment]
I think this issue is quite old, hope that issue is already solved by the time since README file is updated and project is pivoted.
