### ISSUE TITLE
Track screen load duration 

### ISSUE THREAD

**Issue by orhanobut** [orhanobut/tracklytics#13]
## Problem

Sometimes you may need to determine the elapsed time for a specific event. For example: Screen load time between onResume and onCreate
## Proposition

Add a track timer annotation to start point with a key. Key will be used to differentiate different timer points. Thus multiple timer start point can be used. And used a specific annotation to add the attribute which gets the attribute key and the timer to determine elapsed time.

``` java
@TrackTimer("timer_id")
public void onCreate() {}

@TrackEvent("Event name")
@TrackAttribute(key="attribute", timer="timer_id")
public void onResume(){}
```

onResume will have an attribute which is called "attribute" and the value will be elapsed time between onCreate and onTime.

**Comment by sirvon** [comment]
does this work in the source yet?

**Comment by orhanobut** [comment]
No, not yet. I dropped the idea actually until I have a concrete need. Since analytic provides calculate the lead time already. Do you have any concrete example?
