### ISSUE TITLE
How to initialize (Question)

### ISSUE THREAD

**Issue by ergunkocak** [orhanobut/tracklytics#2]
Hi,

Again another great idea and library :+1: 

What should be written to : 

```
   new GoogleAnalyticsTrackingAdapter(this, "CONTAINER_ID", R.raw.container);
```

King regards

**Comment by manjunathc23** [comment]
+1

**Comment by ergunkocak** [comment]
I wrote this very late at night and now i see that question may not be clear :) 
What should be written in place of **CONTAINER_ID** and **R.raw.container**

**Comment by orhanobut** [comment]
Google analytics requires a container which you get it after registration, and it will be replaced automatically. ContainerId is also something like an api key to access google analytics.

**Comment by ergunkocak** [comment]
Very very sorry, i just realised that this is for Google Tag manager not Analytics. Tnx for the explanation
