### ISSUE TITLE
Simple sample project would be great (Suggestion)

### ISSUE THREAD

**Issue by ergunkocak** [orhanobut/tracklytics#3]
@orhanobut first thing first, great library :100:  :) 

I am pretty new to github stuff (dont believe even my profile says other wise :)) so i am writing here my **suggestion** which i believe will increase the user number of library.

it would be great if you can share a simple sample project which contains : 
- tracking of page view, 2 different pages would be more than enough
- tracking of button clicks, 2 different buttons would be more than enough
- integrated with Google Analytics (contains key placeholders)
- integrated with Fabric (contains key placeholders)
  I know it seems nothing but will be very very helpful for many newbies like me and fastens the on boarding process ;)

King Regards

**Comment by orhanobut** [comment]
Thanks for the suggestions really. I'm really looking forward to get more suggestions since I am not expert on the external tools and the usage. This will help a lot. I'll consider these suggestions.

**Comment by orhanobut** [comment]
This project is pivoted a little bit since the beginning. I added a sample to cover most basic stuff. Will be updated soon.

**Comment by orhanobut** [comment]
Ready with version 2.0.0
