### ISSUE TITLE
Track event without annotation

### ISSUE THREAD

**Issue by esafirm** [orhanobut/tracklytics#37]
First things first thanks for the library 👍

My problem is, i don't want to refactor my method just to add `Attribute`s and will not be used in the method itself.

Maybe in my use case i just want to use the annotation for the fixed attribute event.

Is it possible to track event from the `Tracker`? Thanks before

**Comment by orhanobut** [comment]
@esafirm I'm actually adding this and more option for tracking without annotation. In some use cases, indeed it is more easy to just use convenient tracking method.

**Comment by orhanobut** [comment]
Ready with version 2.0.0
