### ISSUE TITLE
Set minifyEnabled to true in release mode causes Exception

### ISSUE THREAD

**Issue by sathi-007** [orhanobut/tracklytics#6]
hi,
Firstly it is a really cool library. Congrats on that. 
But your sample app crashes when minifyEnabled option to true. I believe proguard is causing this exception. I have added this library in my app , same exception occurs when minifyenabled to true. So please give proguard flags to avoid this exception.

i should set minifyEnabled to true to reduce the apk size.

**Comment by orhanobut** [comment]
Currently I'm working on this library for the next version. Indeed the problem is proguard. Each analytic tools requires different proguard files and currently couldn't find enough time to set them.

**Comment by orhanobut** [comment]
#1 This will be followed on this issue. Long story short, I'll add the built-in proguard out of box.
