### ISSUE TITLE
ACRA Integration

### ISSUE THREAD

**Issue by sahal2080** [orhanobut/tracklytics#7]
Lovely library but an issue that I and I assume a growing number of developers are using 
another open source (and personally I think a great library) [ACRA](https://github.com/ACRA/acra). Do you have any plans to integrate with it or extend it?

My hope is to force providers to utilize a single open source library as the interface to tracking/analytics for them all instead of polluting our code as you said.

**Comment by orhanobut** [comment]
After a long time, finally I can spare some time for tracklytics. ACRA looks nice, I need to check how feasible to add, but most probably I can add this.

**Comment by orhanobut** [comment]
All implementations will be up to developers. Thus I'll remove the existing implementations as well. There is already a public interface to provide this. But gonna make it more flexible.
